#image size
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest21?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true

#jwt
jwt:
  secret: JHF*$%5$$ASDAS**OOP
  expiration: 6000000
  header: Authorization

#twilioSettings
twilio:
  accountSid: AC986d9d5372a0d118c7f0f65fda5ed783
  token: a75c35241e51f617eb31c422625fff93