spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest21?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #image size
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true

server:
  port: 8087

#jwt
jwt:
  secret: JHF*$%5$$ASDAS**OOP
  expiration: 6000000
  header: Authorization


